PATIENTS_TABLE = """
IF OBJECT_ID('patients', 'U') IS NULL
CREATE TABLE patients (
    Id NVARCHAR(50) PRIMARY KEY,
    BIRTHDATE DATE,
    DEATHDATE DATE,
    FIRST NVARCHAR(100),
    LAST NVARCHAR(100),
    GENDER NVARCHAR(10),
    CITY NVARCHAR(100),
    STATE NVARCHAR(100)
)
"""

ENCOUNTERS_TABLE = """
IF OBJECT_ID('encounters', 'U') IS NULL
CREATE TABLE encounters (
    Id NVARCHAR(50) PRIMARY KEY,
    PATIENT NVARCHAR(50),
    START DATETIME,
    STOP DATETIME,
    ENCOUNTERCLASS NVARCHAR(50),
    DESCRIPTION NVARCHAR(255)
)
"""

CONDITIONS_TABLE = """
IF OBJECT_ID('conditions', 'U') IS NULL
CREATE TABLE conditions (
    PATIENT NVARCHAR(50),
    ENCOUNTER NVARCHAR(50),
    CODE NVARCHAR(50),
    DESCRIPTION NVARCHAR(255)
)
"""